package com.zcorp.opensportmanagement.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.zcorp.opensportmanagement.dto.MessageDto
import java.time.OffsetDateTime

/**
 * This class does not use the Kotlin feature because for now, there are some constraints due to ReflectDB
 * We ignore the id generated by RethinkDB
 */
@JsonIgnoreProperties(ignoreUnknown = true)
open class Message {
    fun toDto(): MessageDto {
        return MessageDto(body, authorUsername, authorFirstName, authorLastName, conversationId, recipients,
                conversationTopic, time?.toLocalDateTime())
    }

    var body = ""
    var authorUsername = ""   // Username of the author
    var authorFirstName = ""
    var authorLastName = ""
    var recipients: List<Int> = emptyList() // If empty, everyone is targeted. The recipients contain list of team member ids
    var time: OffsetDateTime? = null
    var conversationTopic = ""
    var conversationId = ""
    var teamId: Int? = null
}
