spring:
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false
  datasource:
    url: jdbc:postgresql://localhost:15435/open
    username: postgres
    password: open
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: <your_mail@gmail.com>
    password: <your_mail_password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#logging:
#  level:
#    org.springframework.messaging: trace
#    org.springframework.web.socket: trace
rethinkdb:
  dbhost: '127.0.0.1'
server:
  port: 8090
  ssl:
    key-store-type: PKCS12
    key-store: /home/romainz/opensportmanagement/cert/keystore.p12
    key-store-password: password
    key-alias: opensportmanagement
opensportmanagement:
  events:
    daysBefore: 50
  notifications:
    daysBefore: 7
    enabled: false
  allowedOrigins:
    - https://127.0.0.1:4200
    - https://localhost:4200
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect